### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by william-QAQ** [MerrillLi/LightNestle#1]
尊敬的Yuhui Li师兄：
师兄您好，我是一位研一的研究牲，在拜读完您写的《LightNestle: Quick and Accurate Neural Sequential Tensor Completion via Meta Learning》这篇文章后，我深有感触，迫不及待的去git上面想要复现您的代码，可是尝试了一个星期后，还是因为参数问题没能成功运行...，所以想来问问师兄能否浪费一些时间，把完整的代码文件发一下，期待您的回复。谢谢

**Comment by MerrillLi** [comment]
你好，你可以用邮箱联系我，然后协助您进一步复现。contact me at: liyuhui@hnu.edu.cn

**Comment by MerrillLi** [comment]
> 尊敬的Yuhui Li师兄： 师兄您好，我是一位研一的研究牲，在拜读完您写的《LightNestle: Quick and Accurate Neural Sequential Tensor Completion via Meta Learning》这篇文章后，我深有感触，迫不及待的去git上面想要复现您的代码，可是尝试了一个星期后，还是因为参数问题没能成功运行...，所以想来问问师兄能否浪费一些时间，把完整的代码文件发一下，期待您的回复。谢谢
